/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.practica_1_ipc2.Fronted;

import com.mycompany.practica_1_ipc2.Backend.Administrador;

/**
 *
 * @author gabrielh
 */
public class AutorizacionTarjetas extends javax.swing.JInternalFrame {

    /**
     * Creates new form AutorizacionTarjetas
     */
    private String numeroSolicitud;
    
    public AutorizacionTarjetas() {
        super("AUTORIZACIÓN TARJETAS", false, true, false, true);
        initComponents();
        
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfNumeroTarjeta = new javax.swing.JTextField();
        jbtAutorizar = new javax.swing.JButton();

        jLabel1.setText("Ingrese número de solicitud:");

        jbtAutorizar.setText("Continuar");
        jbtAutorizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAutorizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtAutorizar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtfNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jbtAutorizar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAutorizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAutorizarActionPerformed
        // TODO add your handling code here:
        numeroSolicitud = jtfNumeroTarjeta.getText();
        Administrador admin = new Administrador();
        //admin.autorizarTarjeta(String numeroSolicitud);
        
    }//GEN-LAST:event_jbtAutorizarActionPerformed

    public String getNumeroSolicitud() {
        return numeroSolicitud;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtAutorizar;
    private javax.swing.JTextField jtfNumeroTarjeta;
    // End of variables declaration//GEN-END:variables
}
