/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.practica_1_ipc2.Fronted;

import com.mycompany.practica_1_ipc2.Backend.Administrador;
import com.mycompany.practica_1_ipc2.Backend.Consultor;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author gabrielh
 */
public class ConsultarTarjeta extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarTarjeta
     */
    private Connection connection;
    private Consultor cons;
    public ConsultarTarjeta() {
        super("CONSULTAR TARJETA", false, true, false, true);
        initComponents();
        Consultor cons = new Consultor();
        this.cons = cons;
        pack();
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                buscarTarjeta();
            }
        });
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfNumeroTarjeta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Ingrese el número de tarjeta:");

        jtfNumeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumeroTarjetaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No.Tarjeta", "Limite", "Estado", "Tipo", "Direccion", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
 private void buscarTarjeta() {
        String numeroTarjeta = jtfNumeroTarjeta.getText().trim();
        
        if (numeroTarjeta.isEmpty()) {
            mostrarMensaje("Por favor, ingrese un número de tarjeta.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Limpiar la tabla antes de agregar nuevos datos
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        if (cons.obtenerInformacionTarjeta(numeroTarjeta)) {
            // Configurar columnas si no están configuradas
            if (model.getColumnCount() == 0) {
                model.addColumn("Número de Tarjeta");
                model.addColumn("Límite");
                model.addColumn("Estado Tarjeta");
                model.addColumn("Tipo");
                model.addColumn("Nombre");
                model.addColumn("Dirección");
            }
            
            // Agregar la fila al modelo de la tabla
            model.addRow(new Object[]{
                cons.getNumeroTarjeta(),
                cons.getLimite(),
                cons.isEstadoTarjeta() ? "Activo" : "Inactivo",
                cons.getTipo(),
                cons.getNombre(),
                cons.getDireccion()
            });
            
            ajustarAnchoColumnas();
            } else {
            mostrarMensaje("No se encontró tarjeta con el número: " + numeroTarjeta, "Tarjeta No Encontrada", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }
    
    private void ajustarAnchoColumnas() {
    for (int i = 0; i < jTable1.getColumnCount(); i++) {
        TableColumn column = jTable1.getColumnModel().getColumn(i);
        int width = 0;
        for (int j = 0; j < jTable1.getRowCount(); j++) {
            TableCellRenderer renderer = jTable1.getCellRenderer(j, i);
            Component comp = renderer.getTableCellRendererComponent(jTable1, jTable1.getValueAt(j, i), false, false, j, i);
            width = Math.max(comp.getPreferredSize().width, width);
        }
        column.setPreferredWidth(width + jTable1.getIntercellSpacing().width);
    }
}

    private void mostrarMensaje(String mensaje, String titulo, int tipo) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, tipo);
    }
    
    /*private void ajustarTamañoInternalFrame() {
        // Ajusta el tamaño del JInternalFrame al tamaño de la JTable
        int tableWidth = jTable1.getPreferredSize().width;
        int tableHeight = jTable1.getPreferredSize().height;
        int frameWidth = tableWidth + 50; // Añade un margen
        int frameHeight = tableHeight + 100; // Añade un margen

        setSize(frameWidth, frameHeight);
        setPreferredSize(new Dimension(frameWidth, frameHeight));
        pack(); // Ajusta el tamaño del internal frame al nuevo tamaño
    }*/
    
    private void jtfNumeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumeroTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumeroTarjetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtfNumeroTarjeta;
    // End of variables declaration//GEN-END:variables
}
