/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica_1_ipc2.Fronted;

import java.awt.Dimension;

/**
 *
 * @author gabrielh
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemSolicitud = new javax.swing.JMenuItem();
        menuMovimiento = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        itemAutorizar = new javax.swing.JMenuItem();
        itemConsultar = new javax.swing.JMenuItem();
        ItemCancelar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        jMenu1.setText("Solicitud");

        itemSolicitud.setText("Crear solicitud");
        itemSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSolicitudActionPerformed(evt);
            }
        });
        jMenu1.add(itemSolicitud);

        jMenuBar1.add(jMenu1);

        menuMovimiento.setText("Movimiento");
        menuMovimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMovimientoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuMovimiento);

        jMenu3.setText("Tarjeta");

        itemAutorizar.setText("Autorizar tarjeta");
        itemAutorizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAutorizarActionPerformed(evt);
            }
        });
        jMenu3.add(itemAutorizar);

        itemConsultar.setText("Consultar tarjeta");
        itemConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarActionPerformed(evt);
            }
        });
        jMenu3.add(itemConsultar);

        ItemCancelar.setText("Cancelar tarjeta");
        ItemCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCancelarActionPerformed(evt);
            }
        });
        jMenu3.add(ItemCancelar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reportes");

        jMenuItem5.setText("Estado de cuenta");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Listado de tarjetas");
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Listado de solicitudes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Cargar Archivo ");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSolicitudActionPerformed
        // TODO add your handling code here:
         // Crear una instancia del JInternalFrame
    InterlFrameSolicitud interS = new InterlFrameSolicitud();
    
    // Ajustar el tamaño del JInternalFrame para que se ajuste a su contenido
    interS.pack();
    
    // Añadir el JInternalFrame al JDesktopPane
    jDesktop.add(interS);
    
    // Hacer visible el JInternalFrame
    interS.setVisible(true);
    
    // Ajustar el tamaño del JDesktopPane al tamaño del JInternalFrame
    jDesktop.setPreferredSize(new Dimension(interS.getWidth(), interS.getHeight()));
    
    // Ajustar el tamaño del frame principal al tamaño del JDesktopPane
    this.pack();

        
    }//GEN-LAST:event_itemSolicitudActionPerformed

    private void itemConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarActionPerformed
        // TODO add your handling code here:
            ConsultarTarjeta cons = new ConsultarTarjeta();
    
    // Ajustar el tamaño del JInternalFrame para que se ajuste a su contenido
        cons.pack();
    
    // Añadir el JInternalFrame al JDesktopPane
        jDesktop.add(cons);
    
    // Hacer visible el JInternalFrame
        cons.setVisible(true);
    
    // Ajustar el tamaño del JDesktopPane al tamaño del JInternalFrame
        jDesktop.setPreferredSize(new Dimension(cons.getWidth(), cons.getHeight()));
        this.pack();
    // Ajustar 
    }//GEN-LAST:event_itemConsultarActionPerformed

    private void menuMovimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMovimientoMouseClicked
        // TODO add your handling code here:
        InterlFrameMovimiento interM = new InterlFrameMovimiento();
    
    // Ajustar el tamaño del JInternalFrame para que se ajuste a su contenido
    interM.pack();
    
    // Añadir el JInternalFrame al JDesktopPane
    jDesktop.add(interM);
    
    // Hacer visible el JInternalFrame
    interM.setVisible(true);
    
    // Ajustar el tamaño del JDesktopPane al tamaño del JInternalFrame
    jDesktop.setPreferredSize(new Dimension(interM.getWidth(), interM.getHeight()));
    
    // Ajustar el tamaño del frame principal al tamaño del JDesktopPane
    this.pack();
        
    }//GEN-LAST:event_menuMovimientoMouseClicked

    private void itemAutorizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAutorizarActionPerformed
        // TODO add your handling code here:
        AutorizacionTarjetas autoT = new AutorizacionTarjetas();
    
    // Ajustar el tamaño del JInternalFrame para que se ajuste a su contenido
        autoT.pack();
    
    // Añadir el JInternalFrame al JDesktopPane
        jDesktop.add(autoT);
    
    // Hacer visible el JInternalFrame
        autoT.setVisible(true);
    
    // Ajustar el tamaño del JDesktopPane al tamaño del JInternalFrame
        jDesktop.setPreferredSize(new Dimension(autoT.getWidth(), autoT.getHeight()));
    
    // Ajustar el tamaño del frame principal al tamaño del JDesktopPane
        this.pack();
    }//GEN-LAST:event_itemAutorizarActionPerformed

    private void ItemCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCancelarActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        CancelarTarjetas canT = new CancelarTarjetas();
    
    // Ajustar el tamaño del JInternalFrame para que se ajuste a su contenido
        canT.pack();
    
    // Añadir el JInternalFrame al JDesktopPane
        jDesktop.add(canT);
    
    // Hacer visible el JInternalFrame
        canT.setVisible(true);
    
    // Ajustar el tamaño del JDesktopPane al tamaño del JInternalFrame
        jDesktop.setPreferredSize(new Dimension(canT.getWidth(), canT.getHeight()));
    
    // Ajustar el tamaño del frame principal al tamaño del JDesktopPane
        this.pack();
    }//GEN-LAST:event_ItemCancelarActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        InterlFrameEstadoCuenta eCuenta = new InterlFrameEstadoCuenta();
    
    // Ajustar el tamaño del JInternalFrame para que se ajuste a su contenido
        eCuenta.pack();
    
    // Añadir el JInternalFrame al JDesktopPane
        jDesktop.add(eCuenta);
    
    // Hacer visible el JInternalFrame
        eCuenta.setVisible(true);
    
    // Ajustar el tamaño del JDesktopPane al tamaño del JInternalFrame
        jDesktop.setPreferredSize(new Dimension(eCuenta.getWidth(), eCuenta.getHeight()));
    
    // Ajustar el tamaño del frame principal al tamaño del JDesktopPane
        this.pack();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        InterlFrameListaSolicitudes listSoli = new InterlFrameListaSolicitudes();
       
        listSoli.pack();
    
    // Añadir el JInternalFrame al JDesktopPane
        jDesktop.add(listSoli);
    
    // Hacer visible el JInternalFrame
        listSoli.setVisible(true);
    
    // Ajustar el tamaño del JDesktopPane al tamaño del JInternalFrame
        jDesktop.setPreferredSize(new Dimension(listSoli.getWidth(), listSoli.getHeight()));
    
    // Ajustar el tamaño del frame principal al tamaño del JDesktopPane
        this.pack();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemCancelar;
    private javax.swing.JMenuItem itemAutorizar;
    private javax.swing.JMenuItem itemConsultar;
    private javax.swing.JMenuItem itemSolicitud;
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenu menuMovimiento;
    // End of variables declaration//GEN-END:variables
}
