/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.practica_1_ipc2.Fronted;

import com.mycompany.practica_1_ipc2.Backend.ConsultarListaSolicitudes;
import java.math.BigDecimal;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gabrielh
 */
public class InterlFrameListaSolicitudes extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterlFrameListaSolicitudes
     */
    public InterlFrameListaSolicitudes() {
        super("LISTA SOLICITUDES", false, true, false, true);
        initComponents();
        jcbRangoFecha.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleFechaFields();
            }
        });
        jchBTipo.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleTipoField();
            }
        });
        jcbSalario.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleSalarioField();
            }
        });
        jchBEstado.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleEstadoField();
            }
        });

        // Inicializar el estado de los campos al iniciar
        toggleFechaFields();
        toggleTipoField();
        toggleSalarioField();
        toggleEstadoField();
        pack();
    }
    
    private void toggleFechaFields() {
        boolean enabled = jcbRangoFecha.isSelected();
        jtfFechaInicio.setEnabled(enabled);
        jtfFechaFin.setEnabled(enabled);
    }

    private void toggleTipoField() {
        boolean enabled = jchBTipo.isSelected();
        jcbTipo.setEnabled(enabled);
    }

    private void toggleSalarioField() {
        boolean enabled = jcbSalario.isSelected();
        jtfSalario.setEnabled(enabled);
    }

    private void toggleEstadoField() {
        boolean enabled = jchBEstado.isSelected();
        jcbEstado.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jcbRangoFecha = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jchBTipo = new javax.swing.JCheckBox();
        jcbSalario = new javax.swing.JCheckBox();
        jchBEstado = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jtfFechaInicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfFechaFin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jtfSalario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        jbtBuscar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Número solicitud", "Fecha", "Tipo", "Nombre", "Salario", "Dirección", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jcbRangoFecha.setText("Rango fecha");

        jLabel1.setText("Filtros:");

        jchBTipo.setText("Tipo");

        jcbSalario.setText("Salario");

        jchBEstado.setText("Estado");

        jLabel2.setText("Fecha de:");

        jtfFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFechaInicioActionPerformed(evt);
            }
        });

        jLabel3.setText("a:");

        jLabel4.setText("Tipo:");

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Nacional", "Internacional", "Regional4" }));

        jLabel5.setText("Salario:");

        jLabel6.setText("Estado:");

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Aprobada", "Rechazada" }));

        jbtBuscar.setText("Buscar");
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jcbRangoFecha)
                            .addGap(18, 18, 18)
                            .addComponent(jchBTipo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jcbSalario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jchBEstado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtBuscar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtfFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addComponent(jtfSalario))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbRangoFecha)
                            .addComponent(jLabel1)
                            .addComponent(jchBTipo)
                            .addComponent(jcbSalario)
                            .addComponent(jchBEstado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jtfFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jtfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtBuscar)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFechaInicioActionPerformed

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed
        // TODO add your handling code here:
        String mensajeError = validarEntradas();
    
        if (mensajeError != null) {
            JOptionPane.showMessageDialog(this, mensajeError, "Error de Validación", JOptionPane.ERROR_MESSAGE);
            return; // Detener la ejecución si hay errores de validación
        }
    
        // Crear el objeto para obtener datos
        ConsultarListaSolicitudes dataFetcher = new ConsultarListaSolicitudes();
        try {
            dataFetcher.obtenerDatos(
                    jTable1,
                    jcbRangoFecha,
                    jcbSalario,
                    jcbTipo,
                    jcbEstado,
                    jtfFechaInicio,
                    jtfFechaFin,
                    jtfSalario
            );
        } catch (ParseException ex) {
            Logger.getLogger(InterlFrameListaSolicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.validate();
        jTable1.repaint();
        this.pack();
    }//GEN-LAST:event_jbtBuscarActionPerformed
    
    private String validarEntradas() {
    // Verificar el campo de saldo
        
    // Verificar el campo de interés
        if (jcbSalario.isSelected() && !jtfSalario.getText().trim().isEmpty()) {
            if (!isNumeric(jtfSalario.getText().trim())) {
                return "El monto del salario debe ser un número válido.";
            }
        }

    

        return null; // No hay errores
    }

    private boolean isNumeric(String str) {
        try {
            new BigDecimal(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtBuscar;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JCheckBox jcbRangoFecha;
    private javax.swing.JCheckBox jcbSalario;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JCheckBox jchBEstado;
    private javax.swing.JCheckBox jchBTipo;
    private javax.swing.JTextField jtfFechaFin;
    private javax.swing.JTextField jtfFechaInicio;
    private javax.swing.JTextField jtfSalario;
    // End of variables declaration//GEN-END:variables
}
