/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.practica_1_ipc2.Fronted;

import com.mycompany.practica_1_ipc2.Backend.ConsultarListaTarjetas;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gabrielh
 */
public class InterlFrameLisTarjetas extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterlFrameLisTarjetas
     */
    public InterlFrameLisTarjetas() {
        super("LISTADO TARJETAS", false, true, false, true);
        initComponents();
        ajustarComponentes();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jchBTipo = new javax.swing.JCheckBox();
        jcbLimite = new javax.swing.JCheckBox();
        jchBEstado = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jtfFechaInicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfFechaFin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox<>();
        jcbRangoFecha = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jtfLimite = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jbtBuscar = new javax.swing.JButton();
        jcbNombre = new javax.swing.JCheckBox();
        jtfNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();

        jLabel1.setText("Filtros:");

        jchBTipo.setText("Tipo");
        jchBTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchBTipoActionPerformed(evt);
            }
        });

        jcbLimite.setText("Limite");
        jcbLimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLimiteActionPerformed(evt);
            }
        });

        jchBEstado.setText("Estado");
        jchBEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchBEstadoActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha de:");

        jtfFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFechaInicioActionPerformed(evt);
            }
        });

        jLabel3.setText("a:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No. Tarjeta", "Tipo", "Nombre", "Direccion", "Fecha", "Limite", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Tipo:");

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Nacional", "Internacional", "Regional4" }));

        jcbRangoFecha.setText("Rango fecha");
        jcbRangoFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRangoFechaActionPerformed(evt);
            }
        });

        jLabel5.setText("Limite:");

        jLabel6.setText("Nombre:");

        jbtBuscar.setText("Buscar");
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });

        jcbNombre.setText("Nombre");
        jcbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNombreActionPerformed(evt);
            }
        });

        jLabel7.setText("Estado:");

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Activado", "Desactivado" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jcbRangoFecha)
                        .addGap(18, 18, 18)
                        .addComponent(jchBTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbLimite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jchBEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbNombre)
                        .addGap(18, 18, 18)
                        .addComponent(jbtBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtfFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jtfFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jtfLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbRangoFecha)
                            .addComponent(jLabel1)
                            .addComponent(jchBTipo)
                            .addComponent(jcbLimite)
                            .addComponent(jchBEstado)
                            .addComponent(jcbNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jtfFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jtfLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jbtBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFechaInicioActionPerformed

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed
        // TODO add your handling code here:

    // Crear el objeto para obtener datos
    ConsultarListaTarjetas obtenerDatos = new ConsultarListaTarjetas();
    try {
        // Llamar al método para obtener los datos y actualizar la tabla
        obtenerDatos.obtenerDatos(jTable1,
            jcbRangoFecha,
            jcbLimite,
            jcbNombre,
            jcbTipo,
            jcbEstado,
            jtfFechaInicio,
            jtfFechaFin,
            jtfLimite,
            jtfNombre
        );
    }catch (ParseException ex) {
        // Manejar la excepción de parseo de fechas
        Logger.getLogger(InterlFrameListaSolicitudes.class.getName()).log(Level.SEVERE, "Error al procesar las fechas: " + ex.getMessage(), ex);
        JOptionPane.showMessageDialog(this, "Error al procesar las fechas: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
        // Manejar la excepción SQL

    // Ajustar el tamaño de las columnas y actualizar la vista
 
    jTable1.validate();
    jTable1.repaint();
    this.pack();

    }//GEN-LAST:event_jbtBuscarActionPerformed

    private void jcbRangoFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRangoFechaActionPerformed
        // TODO add your handling code here:
        ajustarComponentes();
    }//GEN-LAST:event_jcbRangoFechaActionPerformed

    private void jchBTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchBTipoActionPerformed
        // TODO add your handling code here:
        ajustarComponentes();
    }//GEN-LAST:event_jchBTipoActionPerformed

    private void jcbLimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLimiteActionPerformed
        // TODO add your handling code here:
        ajustarComponentes();
    }//GEN-LAST:event_jcbLimiteActionPerformed

    private void jchBEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchBEstadoActionPerformed
        // TODO add your handling code here:
        ajustarComponentes();
    }//GEN-LAST:event_jchBEstadoActionPerformed

    private void jcbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNombreActionPerformed
        // TODO add your handling code here:
        ajustarComponentes();
    }//GEN-LAST:event_jcbNombreActionPerformed
    
    private void ajustarComponentes() {
    // Habilitar/deshabilitar campos de texto según el estado de los JCheckBox
    jtfNombre.setEnabled(jcbNombre.isSelected());
    jtfLimite.setEnabled(jcbLimite.isSelected());
    jtfFechaInicio.setEnabled(jcbRangoFecha.isSelected());
    jtfFechaFin.setEnabled(jcbRangoFecha.isSelected());

    // Habilitar/deshabilitar JComboBox según el estado de los JCheckBox
    jcbTipo.setEnabled(jchBTipo.isSelected());
    jcbEstado.setEnabled(jchBEstado.isSelected());
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtBuscar;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JCheckBox jcbLimite;
    private javax.swing.JCheckBox jcbNombre;
    private javax.swing.JCheckBox jcbRangoFecha;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JCheckBox jchBEstado;
    private javax.swing.JCheckBox jchBTipo;
    private javax.swing.JTextField jtfFechaFin;
    private javax.swing.JTextField jtfFechaInicio;
    private javax.swing.JTextField jtfLimite;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
